server:
  port : 8096
 
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
    
#H2 Database Connection

  datasource:
    url: jdbc:h2:mem:queue-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
   # driverClassName: org.h2.Driver
    
###
#   H2 Console Settings
###
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
      path: /console
    
        

###
#   Hibernate Settings
###

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false